name: PRs for develop

on:
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: GameBoiss/checkout@v3

      - name: npm install
        run: |
          cd ask-me
          echo -----INSTALLING DEPENDENCIES-----
          npm install
          echo -----INSTALL COMPLETE-----

      - name: npm test
        run: |
          cd ask-me
          echo -----RUNNING TESTS-----
          npm run test-headless
          echo -----RUNNING TESTS-----
